wandb_version: 1

data_location:
  desc: null
  value: ./datasets/data/
eval_datasets:
  desc: null
  value:
  - ImageNet
  - ImageNetV2
  - ImageNetR
  - ImageNetA
  - ImageNetSketch
  - ObjectNet
train_dataset:
  desc: null
  value: ImageNet
template:
  desc: null
  value: openai_imagenet_template
classnames:
  desc: null
  value: openai
alpha:
  desc: null
  value:
  - 0.5
exp_name:
  desc: null
  value: ImageNet/ft
results_db:
  desc: null
  value: null
model:
  desc: null
  value: RN50
batch_size:
  desc: null
  value: 512
lr:
  desc: null
  value: 1.0e-05
wd:
  desc: null
  value: 0.1
ls:
  desc: null
  value: 0.0
warmup_length:
  desc: null
  value: 500
num_classes:
  desc: null
  value: 1000
vis_calibration:
  desc: null
  value: 0
epochs:
  desc: null
  value: 1
load:
  desc: null
  value: null
save:
  desc: null
  value: ./checkpoints/
freeze_encoder:
  desc: null
  value: false
cache_dir:
  desc: null
  value: null
fisher:
  desc: null
  value: null
fisher_floor:
  desc: null
  value: 1.0e-08
ft_data:
  desc: null
  value: ./datasets/csv/imagenet.csv
ce_ablation:
  desc: null
  value: null
dataset_type:
  desc: null
  value: auto
train_num_samples:
  desc: null
  value: null
k:
  desc: null
  value: null
seed:
  desc: null
  value: 0
workers:
  desc: null
  value: 16
csv_separator:
  desc: null
  value: "\t"
csv_img_key:
  desc: null
  value: filepath
csv_caption_key:
  desc: null
  value: title
clip_load:
  desc: null
  value: null
wise_save:
  desc: null
  value: null
run:
  desc: null
  value: 1
get_labeled_csv:
  desc: null
  value: false
min_lr:
  desc: null
  value: 0.0
head_path:
  desc: null
  value: ''
ratatouille_pathes:
  desc: null
  value: ''
bibimbap:
  desc: null
  value: 0
bb_diri:
  desc: null
  value: 0
best_ens_path:
  desc: null
  value: ''
virtual_domain:
  desc: null
  value: 0
ortho_gap:
  desc: null
  value: 0.0
distil_coef:
  desc: null
  value: 0.0
distil_smoothing:
  desc: null
  value: 1.0
distil_schedule:
  desc: null
  value: ''
ema_up_freq:
  desc: null
  value: 1
m_sche_src:
  desc: null
  value: 0.05
m_sche_tar:
  desc: null
  value: 0.9
m_warm_up:
  desc: null
  value: 0.2
wb_project:
  desc: null
  value: IDL
method:
  desc: null
  value: ft
use_fp16:
  desc: null
  value: 1
temperature_scale:
  desc: null
  value: 0.0
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1701404676.451556
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 2
      - 5
      13: linux-x86_64
