# Properties
OUTPUT_DIRECTORY = "output_directory"
MODEL = "model"
VISUALIZATION_LAYER = "visualization_layer"
LINEAR_PROBE_LAYER = "linear_probe_layer"
OBJECTIVE = "objective"
OPTIMIZER = "optimizer"
NUMBER_OF_ITERATIONS = "num_iterations"
LEARNING_RATE = "learning_rate"
CHANNEL = "channel"
PROBES_DIRECTORY = "probe_checkpoint_directory"
CHECKPOINT_FILENAME = "linear_probe_model"
IMAGE_HEIGHT = "image_h"
IMAGE_WIDTH = "image_w"
IMG_DECORRELATE = "img_use_decorrelate"
IMG_FFT = "img_use_fft"

ADAM = "Adam"
ADAM_W = "AdamW"
SGD = "SGD"